### ISSUE TITLE
Less ugly fonts and gtk look and feel ?

### ISSUE THREAD

**Issue by solsticedhiver** [bannsec/autopsy_docker#5]
It's been a while since I used docker, so I don't know how to actually use the tips and tricks at https://wiki.archlinux.org/index.php/Java#Better_font_rendering

to get better font looking and eventually GTK look and feel with a java app running in docker ...

May be you do, and you can even make it a default, if it's in the docker image that this needs to happen ?

**Comment by bannsec** [comment]
The UI for Autopsy is provided by the tool itself. This is just a docker image to use the tool. You probably want to talk to the autopsy devs about it.

**Comment by solsticedhiver** [comment]
In case you did not follow the link, by using an environnment var, you can change the way the java GUI looks, that is fixed it so that it look better.

The dev have nothing to do with it.

But you are free to close this if you think you are not concerned

**Comment by fam4r** [comment]
I'm working on that, if @bannsec agrees i can make a PR

**Comment by bannsec** [comment]
go for it :)

**Comment by fam4r** [comment]
@solsticedhiver Please try my fork before I make a PR to this upstream

https://github.com/fam4r/autopsy_docker/commit/d258c08c7a0846b179ca38c7a01f1fea872852a6

I see no difference while running Autopsy, but can solve your request.

I both tried `_JAVA_OPTIONS` (the one suggested into the Arch Wiki) and `JAVA_TOOL_OPTIONS` (which [seems to be](https://bugs.openjdk.java.net/browse/JDK-4971166) the standard) environment variables.
I can confirm they are used by Java because of the following log

```
Attaching to autopsy
autopsy    | Picked up JAVA_TOOL_OPTIONS: [...]
```

but I am not noticing any difference.

You can try yourself by editing the relevant line
https://github.com/fam4r/autopsy_docker/blob/master/docker-compose.yml#L12

**Comment by fam4r** [comment]
Oh, ok, I found the problem: we have to send the environment variable without quotes:
```
JAVA_TOOL_OPTIONS=-D...
```
instead of 
```
JAVA_TOOL_OPTIONS='-D...'
```

https://github.com/fam4r/autopsy_docker/commit/e8822cebc8c0fd39a55822041890e911bd3870b0

But... there is one more issue to solve: as reported by the Arch Wiki (and I tested that), the default GTK Look and Feel used by Java is GTK 2, so the only way to change that is to use Java >= 9 which allows the use of `jdk.gtk.version=3` property.

Using GTK 2, IMHO, it will not be "less ugly".

I'm going to provide a PR with the only support for full anti-aliasing enabled.

**Comment by solsticedhiver** [comment]
I am using 
```
$ docker run \
            -d \
            -it \
            --shm-size 2G \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -v ./case/:/root/case \
            -e DISPLAY=$DISPLAY \
            -e _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'    \
            --network host \
            bannsec/autopsy
```
and I got what I expected. better looking font.

May be you could change the docker command in the README.md too ? or add a note ?

I think the change of the font would mostly be visible in the right pane.

Also docker does not like './case/' and wants an absolute path.

@fam4r and yes you are right for gtk 3 look and feel we need java 9. But better looking font and swing widget is already better. and gtk 2 is ugly though

**Comment by simonbh** [comment]
Building on this, here is the docker-compose.yml file that has these additions:
```

version: "3"
services:
    autopsy:
        image: bannsec/autopsy:latest
        container_name: autopsy
        shm_size: "2gb"
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ./case/:/root/case
        environment:
          - DISPLAY=${DISPLAY}
          - JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
        networks:
          - host
        devices:
          - "/dev/dri:/dev/dri"
networks:
    host:
```
